[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "databridge-client"
version = "0.1.0"
description = "Python client for DataBridge RAG service"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.24.0",
    "pyjwt>=2.0.0"
]

[project.optional-dependencies]
dev = ["pytest", "pytest-asyncio", "black", "isort"]
